/**
 * Auto-Generated Billing Tab
 * 
 * Shows treatments automatically pulled from clinical module
 * Allows review and removal before finalizing invoice
 */

"use client";

import { motion, AnimatePresence } from "framer-motion";
import { Check, X, AlertCircle, Stethoscope } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useBillingStore } from "@/lib/billing-store";
import { cn } from "@/lib/utils";

export function AutoGeneratedTab() {
    const { autoItems, removeAutoItem, items } = useBillingStore();

    if (autoItems.length === 0) {
        return (
            <div className="flex flex-col items-center justify-center py-20 text-center">
                <div className="w-20 h-20 bg-indigo-50 rounded-full flex items-center justify-center mb-6">
                    <Stethoscope className="w-10 h-10 text-indigo-300" />
                </div>
                <h3 className="text-lg font-bold text-slate-900">No Clinical Treatments Yet</h3>
                <p className="text-slate-500 text-sm max-w-sm mt-2">
                    Treatments marked as "done" by the doctor will appear here automatically with calculated charges.
                </p>
            </div>
        );
    }

    return (
        <div className="space-y-4">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div>
                    <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">
                        Auto-Generated from Clinical
                    </h3>
                    <p className="text-xs text-slate-500 mt-1">
                        {autoItems.length} item{autoItems.length !== 1 ? 's' : ''} from doctor's treatment records
                    </p>
                </div>
                <div className="flex items-center gap-2 text-xs text-green-600 bg-green-50 px-3 py-1.5 rounded-full">
                    <Check className="w-3 h-3" />
                    <span className="font-semibold">Smart Billing Active</span>
                </div>
            </div>

            {/* Treatment List */}
            <AnimatePresence mode="popLayout">
                {autoItems.map((item, index) => (
                    <motion.div
                        key={item.id}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.95 }}
                        transition={{ delay: index * 0.05 }}
                        className={cn(
                            "bg-white border-2 border-indigo-100 rounded-xl p-4 hover:border-indigo-300 transition-colors",
                            "relative overflow-hidden"
                        )}
                    >
                        {/* Auto-badge */}
                        <div className="absolute top-2 right-2 bg-indigo-600 text-white text-[9px] font-black uppercase tracking-wider px-2 py-0.5 rounded-full">
                            Auto
                        </div>

                        {/* Content Grid */}
                        <div className="grid grid-cols-[1fr_auto] gap-4 items-start">
                            {/* Left: Treatment Info */}
                            <div className="space-y-2">
                                <div>
                                    <h4 className="text-sm font-bold text-slate-900">{item.name}</h4>
                                    {item.metadata?.category && (
                                        <p className="text-xs text-slate-500 mt-0.5">
                                            Category: {item.metadata.category}
                                        </p>
                                    )}
                                </div>

                                {/* Teeth treated */}
                                {item.metadata?.teethTreated && item.metadata.teethTreated.length > 0 && (
                                    <div className="flex items-center gap-2 text-xs">
                                        <span className="font-semibold text-slate-600">Teeth:</span>
                                        <div className="flex gap-1">
                                            {item.metadata.teethTreated.map(tooth => (
                                                <span
                                                    key={tooth}
                                                    className="bg-slate-100 text-slate-700 px-2 py-0.5 rounded font-mono text-xs"
                                                >
                                                    {tooth}
                                                </span>
                                            ))}
                                        </div>
                                    </div>
                                )}

                                {/* Calculation breakdown */}
                                <div className="flex items-center gap-4 text-xs text-slate-600">
                                    <div>
                                        <span className="font-semibold">Rate:</span> ₹{item.baseCost.toLocaleString('en-IN')}
                                    </div>
                                    <div>
                                        <span className="font-semibold">Qty:</span> {item.quantity}
                                    </div>
                                    <div>
                                        <span className="font-semibold">Tax:</span> {item.taxRate}%
                                    </div>
                                </div>

                                {/* Completed timestamp */}
                                {item.metadata?.completedAt && (
                                    <p className="text-[10px] text-slate-400">
                                        Completed: {new Date(item.metadata.completedAt).toLocaleString('en-IN', {
                                            month: 'short',
                                            day: 'numeric',
                                            hour: '2-digit',
                                            minute: '2-digit'
                                        })}
                                    </p>
                                )}
                            </div>

                            {/* Right: Amount & Actions */}
                            <div className="flex flex-col items-end gap-3">
                                {/* Amount */}
                                <div className="text-right">
                                    <div className="text-2xl font-black text-indigo-600">
                                        ₹{(item.baseCost * item.quantity).toLocaleString('en-IN')}
                                    </div>
                                    {item.taxRate > 0 && (
                                        <div className="text-[10px] text-slate-500 mt-0.5">
                                            +₹{((item.baseCost * item.quantity) * (item.taxRate / 100)).toLocaleString('en-IN')} tax
                                        </div>
                                    )}
                                </div>

                                {/* Remove button */}
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={() => removeAutoItem(item.id)}
                                    className="text-red-600 hover:text-red-700 hover:bg-red-50 h-8 px-3"
                                >
                                    <X className="w-3 h-3 mr-1" />
                                    <span className="text-xs font-semibold">Remove</span>
                                </Button>
                            </div>
                        </div>
                    </motion.div>
                ))}
            </AnimatePresence>

            {/* Info Banner */}
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
                <div className="text-xs text-blue-700">
                    <p className="font-semibold">Smart Billing Active</p>
                    <p className="mt-1 leading-relaxed">
                        These charges were automatically calculated based on treatments marked complete by the doctor.
                        You can remove any item that shouldn't be billed. Switch to "Manual Entry" tab to add additional charges.
                    </p>
                </div>
            </div>
        </div>
    );
}
