"use client";

import { useState, useEffect } from "react";
import { InvoiceGenerator } from "@/components/billing/invoice-generator";
import { AutoGeneratedTab } from "@/components/billing/auto-generated-tab";
import { ManualEntryTab } from "@/components/billing/manual-entry-tab";

import { PanzeCard } from "@/components/ui/panze-card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { TrendingUp, Receipt, Sparkles, Edit, RefreshCw, Eye, EyeOff, CheckCircle2 } from "lucide-react";
import { useBillingStore } from "@/lib/billing-store";
import { useSchedulingStore } from "@/lib/scheduling-store"; // For Revenue Privacy
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

export default function BillingPage() {
    const { mode, switchMode, autoItems, items } = useBillingStore();
    const billingStore = useBillingStore(); // Access for other actions if needed

    // Revenue Privacy from Scheduling Store
    const { showRevenue, toggleRevenueVisibility, clinicDetails } = useSchedulingStore();

    // Stats (Mocked for now, should come from a store or API)
    const todaysRevenue = 45200;
    const pendingInvoices = 3;

    // Sync animation state
    const [isSyncing, setIsSyncing] = useState(false);

    const handleSync = () => {
        setIsSyncing(true);
        // Simulate sync
        setTimeout(() => {
            setIsSyncing(false);
            toast.success("Synced with clinical records");
        }, 1500);
    };

    return (
        <div className="flex flex-col gap-6 h-[calc(100vh-8rem)] bg-white">
            {/* Top Stats Row - Noble White / Glass Aesthetic */}
            <div className="grid grid-cols-1 md:grid-cols-12 gap-4 h-32 flex-shrink-0">

                {/* 1. Today's Revenue (Noble Glass + Privacy) */}
                <div className="md:col-span-3 relative group overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm p-5 flex flex-col justify-between transition-all hover:shadow-md">
                    <div className="flex justify-between items-start z-10">
                        <div>
                            <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Today's Revenue</p>
                            <div className="mt-1 flex items-center gap-3">
                                <h3 className={cn(
                                    "text-2xl font-black text-slate-900 transition-all duration-300",
                                    !showRevenue && "blur-md select-none opacity-50"
                                )}>
                                    {new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(todaysRevenue)}
                                </h3>
                            </div>
                        </div>
                        <button
                            onClick={toggleRevenueVisibility}
                            className="p-2 rounded-full hover:bg-slate-50 text-slate-400 hover:text-slate-600 transition-colors"
                        >
                            {showRevenue ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                        </button>
                    </div>
                    <div className="flex items-center gap-2 text-[10px] font-medium text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full w-fit">
                        <TrendingUp className="w-3 h-3" />
                        +12% vs yesterday
                    </div>
                    {/* Glass Decor */}
                    <div className="absolute -right-4 -bottom-4 w-24 h-24 bg-slate-50 rounded-full blur-2xl opacity-50 pointer-events-none" />
                </div>

                {/* 2. Smart Billing Hub (Center Piece) */}
                <div className="md:col-span-6 rounded-2xl border border-indigo-50 bg-indigo-50/30 p-5 flex items-center justify-between relative overflow-hidden">
                    <div className="z-10">
                        <div className="flex items-center gap-2 mb-2">
                            <div className="p-1.5 bg-indigo-100 rounded-lg">
                                <Sparkles className="w-4 h-4 text-indigo-600" />
                            </div>
                            <h4 className="text-sm font-black text-indigo-950 uppercase tracking-wide">Smart Ledger</h4>
                        </div>
                        <p className="text-xs text-indigo-800/70 max-w-[280px] leading-relaxed">
                            {autoItems.length} clinical procedures pending to be billed.
                            <span className="block opacity-60 text-[10px] mt-1">Last synced: Just now</span>
                        </p>
                    </div>

                    <div className="flex gap-8 items-center z-10 mr-4">
                        <div className="text-center">
                            <span className="block text-2xl font-black text-indigo-600">{autoItems.length}</span>
                            <span className="text-[10px] font-bold text-indigo-400 uppercase">Auto</span>
                        </div>
                        <div className="w-px h-8 bg-indigo-200" />
                        <div className="text-center">
                            <span className="block text-2xl font-black text-slate-600">{items.length}</span>
                            <span className="text-[10px] font-bold text-slate-400 uppercase">Total</span>
                        </div>
                    </div>

                    {/* Background Pattern */}
                    <div className="absolute inset-0 opacity-[0.03] bg-[radial-gradient(#4f46e5_1px,transparent_1px)] [background-size:16px_16px]" />
                </div>

                {/* 3. Pending Invoices */}
                <div className="md:col-span-3 rounded-2xl border border-slate-100 bg-white shadow-sm p-5 flex flex-col justify-center items-center gap-2 text-center group hover:border-orange-100 transition-colors">
                    <div className="w-10 h-10 rounded-full bg-orange-50 text-orange-500 flex items-center justify-center group-hover:scale-110 transition-transform">
                        <Receipt className="w-5 h-5" />
                    </div>
                    <div>
                        <span className="text-xl font-black text-slate-900">{pendingInvoices}</span>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Unpaid Invoices</p>
                    </div>
                </div>

            </div>

            {/* Main Workspace - "Split Ledger" Layout */}
            <div className="flex-1 flex gap-8 min-h-0">

                {/* LEFT: Working Area (Tabs) */}
                <div className="flex-1 min-w-0 flex flex-col">
                    <Tabs
                        value={mode}
                        onValueChange={(value) => switchMode(value as 'auto' | 'manual')}
                        className="flex flex-col h-full"
                    >
                        <div className="flex items-center justify-between mb-4">
                            <TabsList className="grid w-[300px] grid-cols-2 bg-slate-100 p-1 rounded-xl h-10">
                                <TabsTrigger
                                    value="auto"
                                    className="data-[state=active]:bg-white data-[state=active]:text-indigo-600 data-[state=active]:shadow-sm rounded-lg text-[11px] font-bold uppercase tracking-wider gap-2"
                                >
                                    Auto-Sync
                                    {autoItems.length > 0 && (
                                        <span className="bg-indigo-600 text-white px-1.5 py-0.5 rounded-full text-[9px] font-black">
                                            {autoItems.length}
                                        </span>
                                    )}
                                </TabsTrigger>
                                <TabsTrigger
                                    value="manual"
                                    className="data-[state=active]:bg-white data-[state=active]:text-slate-900 data-[state=active]:shadow-sm rounded-lg text-[11px] font-bold uppercase tracking-wider"
                                >
                                    Manual Entry
                                </TabsTrigger>
                            </TabsList>

                            {/* Sync Button (Visible only in Auto mode ideally, but useful generally) */}
                            {mode === 'auto' && (
                                <Button
                                    variant="outline"
                                    size="sm"
                                    onClick={handleSync}
                                    disabled={isSyncing}
                                    className="h-9 text-xs font-bold gap-2 border-slate-200 hover:bg-slate-50"
                                >
                                    <RefreshCw className={cn("w-3.5 h-3.5", isSyncing && "animate-spin")} />
                                    {isSyncing ? "Syncing..." : "Sync Treatments"}
                                </Button>
                            )}
                        </div>

                        <div className="flex-1 rounded-2xl border border-slate-100 bg-slate-50/50 overflow-hidden relative">
                            {/* Inner shadow for depth */}
                            <div className="absolute inset-x-0 top-0 h-4 bg-gradient-to-b from-slate-100/50 to-transparent z-10 pointer-events-none" />

                            <div className="absolute inset-0 overflow-y-auto custom-scrollbar p-1">
                                <TabsContent value="auto" className="mt-0 h-full focus-visible:outline-none">
                                    <AutoGeneratedTab />
                                </TabsContent>

                                <TabsContent value="manual" className="mt-0 h-full focus-visible:outline-none">
                                    <ManualEntryTab />
                                </TabsContent>
                            </div>
                        </div>
                    </Tabs>
                </div>

                {/* RIGHT: Live Invoice (Physical Paper Look) */}
                <div className="w-[480px] flex-shrink-0 flex flex-col h-full relative perspective-1000">
                    {/* Glass/Desk Background Effect for the container */}
                    <div className="absolute inset-0 bg-slate-100/50 rounded-3xl -z-10 blur-xl" />

                    {/* The "Paper" Invoice */}
                    <div className="flex-1 bg-white rounded-xl shadow-[0_20px_50px_-12px_rgba(0,0,0,0.1)] border border-slate-100 overflow-hidden flex flex-col relative">
                        {/* Paper Texture/Gradient */}
                        <div className="absolute inset-0 bg-gradient-to-b from-white to-slate-50/30 pointer-events-none" />

                        <div className="relative flex-1 flex flex-col z-10">
                            <InvoiceGenerator />
                        </div>
                    </div>

                    {/* Printer Floating Action (Optional) */}
                    <div className="absolute -right-12 top-0 flex flex-col gap-3">
                        <div className="w-1 h-12 bg-slate-200 rounded-full mx-auto" />
                        {/* Decorative side elements could go here */}
                    </div>
                </div>

            </div>
        </div>
    );
}
