"use client";

import { useState } from "react";
import { InvoiceGenerator } from "@/components/billing/invoice-generator";
import { AutoGeneratedTab } from "@/components/billing/auto-generated-tab";
import { ManualEntryTab } from "@/components/billing/manual-entry-tab";
import { SmartBillingDemo } from "@/components/billing/smart-billing-demo";
import { PanzeCard } from "@/components/ui/panze-card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { TrendingUp, Receipt, Sparkles, Edit } from "lucide-react";
import { useBillingStore } from "@/lib/billing-store";

export default function BillingPage() {
    const { mode, switchMode, autoItems, items } = useBillingStore();
    const totals = useBillingStore(state => state.getTotals());

    return (
        <div className="flex flex-col gap-6 h-[calc(100vh-8rem)]">
            {/* Top Stats Row */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 h-32 flex-shrink-0">
                {/* Today's Revenue */}
                <PanzeCard className="bg-indigo-600 text-white flex flex-col justify-between">
                    <div className="flex justify-between items-start">
                        <div>
                            <p className="text-xs font-medium opacity-80 uppercase tracking-widest">Today's Revenue</p>
                            <h3 className="text-2xl font-black mt-1">₹0</h3>
                        </div>
                        <div className="p-2 bg-white/10 rounded-lg">
                            <TrendingUp className="w-5 h-5 text-indigo-100" />
                        </div>
                    </div>
                    <div className="text-[10px] bg-white/10 px-2 py-1 rounded inline-self-start w-fit">
                        No transactions yet
                    </div>
                </PanzeCard>

                {/* Smart Billing Status */}
                <PanzeCard className="md:col-span-2 flex flex-col justify-between bg-gradient-to-br from-purple-50 to-indigo-50 border-purple-200">
                    <div className="flex items-center justify-between">
                        <div>
                            <div className="flex items-center gap-2">
                                <Sparkles className="w-4 h-4 text-purple-600" />
                                <h4 className="text-xs font-black uppercase text-purple-900">Smart Billing</h4>
                            </div>
                            <p className="text-xs text-purple-700 mt-1">
                                Auto-generated from clinical treatments
                            </p>
                        </div>
                        <div className="bg-purple-600 text-white px-3 py-1.5 rounded-full text-xs font-black">
                            {autoItems.length} Auto
                        </div>
                    </div>
                    <div className="mt-3 grid grid-cols-2 gap-2 text-xs">
                        <div className="bg-white/60 rounded-lg p-2">
                            <span className="text-purple-600 font-semibold">Auto Items:</span>
                            <span className="text-purple-900 font-black ml-1">{autoItems.length}</span>
                        </div>
                        <div className="bg-white/60 rounded-lg p-2">
                            <span className="text-purple-600 font-semibold">Total Items:</span>
                            <span className="text-purple-900 font-black ml-1">{items.length}</span>
                        </div>
                    </div>
                </PanzeCard>

                {/* Pending Invoices */}
                <PanzeCard className="flex flex-col justify-center items-center gap-2 border-dashed bg-slate-50/50">
                    <div className="w-10 h-10 rounded-full bg-slate-200 flex items-center justify-center">
                        <Receipt className="w-5 h-5 text-slate-400" />
                    </div>
                    <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Pending Invoices</p>
                    <span className="text-xl font-black text-slate-900">0</span>
                </PanzeCard>
            </div>

            {/* Smart Billing Demo Widget */}
            <SmartBillingDemo />

            {/* Main Workspace with Tabs */}
            <div className="flex-1 flex gap-6 min-h-0">
                {/* Left Pane: Tabbed Billing Input */}
                <div className="flex-1 min-w-0 flex flex-col overflow-hidden">
                    <Tabs
                        value={mode}
                        onValueChange={(value) => switchMode(value as 'auto' | 'manual')}
                        className="flex flex-col h-full"
                    >
                        {/* Tab Headers */}
                        <TabsList className="grid w-full grid-cols-2 mb-4 bg-slate-100 p-1 rounded-xl h-12">
                            <TabsTrigger
                                value="auto"
                                className="data-[state=active]:bg-white data-[state=active]:shadow-sm rounded-lg text-xs font-bold uppercase tracking-wider gap-2"
                            >
                                <Sparkles className="w-4 h-4" />
                                <span>Auto-Generated</span>
                                {autoItems.length > 0 && (
                                    <span className="bg-purple-600 text-white px-1.5 py-0.5 rounded-full text-[9px] font-black">
                                        {autoItems.length}
                                    </span>
                                )}
                            </TabsTrigger>
                            <TabsTrigger
                                value="manual"
                                className="data-[state=active]:bg-white data-[state=active]:shadow-sm rounded-lg text-xs font-bold uppercase tracking-wider gap-2"
                            >
                                <Edit className="w-4 h-4" />
                                <span>Manual Entry</span>
                            </TabsTrigger>
                        </TabsList>

                        {/* Tab Content */}
                        <div className="flex-1 overflow-y-auto custom-scrollbar pr-2">
                            <TabsContent value="auto" className="mt-0 focus-visible:outline-none focus-visible:ring-0">
                                <AutoGeneratedTab />
                            </TabsContent>

                            <TabsContent value="manual" className="mt-0 focus-visible:outline-none focus-visible:ring-0">
                                <ManualEntryTab />
                            </TabsContent>
                        </div>
                    </Tabs>
                </div>

                {/* Right Pane: Live Invoice Preview */}
                <div className="w-[450px] flex-shrink-0 flex flex-col bg-white dark:bg-slate-900 border rounded-xl shadow-lg overflow-hidden h-full">
                    <InvoiceGenerator />
                </div>
            </div>
        </div>
    );
}
